import "./globals.css"
import "./css-reset.css"
import { Inter, Dancing_Script } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })
const dancingScript = Dancing_Script({ subsets: ["latin"] })

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={dancingScript.className}>{children}</body>
        </html>
    )
}
